### ISSUE TITLE
Secure Gateway + Docker access error due to localhost not being available

### ISSUE THREAD

**Issue by jthomas** [IBM/ibm-cloud-functions-with-on-prem-resources#1]
## issue

Step 8 in the [Secure Gateway setup](https://github.com/IBM/ibm-cloud-functions-with-on-prem-resources/blob/master/secure-gateway-connection.md) documentation allows the user to choose which installation method they use.

```
On the Clients tab, click on Connect Client and download the appropiate installer for your system. Then run the Secure Gateway Client and enter your Gateway ID and Security Token.
```

I chose Docker as the demo already uses this tool for running the application services. This causes an issue with the port forwarding because the setup instructions use `127.0.0.1` as the on-premise host. Running the Secure Gateway in a container means `127.0.0.1` refers to localhost on the secure gateway container, not the docker host.

### work-around

I managed to [fix this](https://docs.docker.com/docker-for-windows/networking/#there-is-no-docker0-bridge-on-windows) by using `host.docker.internal` as the local hostname for forwarding and set the same value in the ACLs. This is a special hostname configured by Docker which refers to the container host.

## repo fix

I think we should guide the user towards the Docker-based installation of the Secure Gateway service. This would match the other services they are running locally. If so, can we update the instructions and the hostnames/acls to match the work-around above? It would be good to add a few more images + instructions for the Docker command.

We could alternatively include both hostnames for each installation method and make it explicit in the documentation which one to choose. I think this could cause users to make mistakes and pick the wrong one. 

What do you think?

**Comment by AnthonyAmanse** [comment]
@jthomas I think one solution would be to use `--network=host` in the docker run arguments instead of using "host.docker.internal" so that the ACL's will be consistent to 127.0.0.1 and users will not make a mistake by choosing the wrong one.

Open PR #2
